# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/noetarbouriech"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/noe-tarbouriech/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "email"
name = "Send me an email"
url = "mailto:noe.tarbouriech@posteo.net"

[social.params]
icon = "mail"

[[social]]
identifier = "rss"
name = "RSS Feed"
url = "/index.xml"

[social.params]
icon = "rss"
